const ADD_STRING = 'ADD_STRING';
const DEL_STRING = 'DEL_STRING';
const ADD_COMPONENT = 'ADD_COMPONENT';
const DEL_COMPONENT = 'DEL_COMPONENT';

export {
  ADD_STRING,
  DEL_STRING,
  ADD_COMPONENT,
  DEL_COMPONENT,
};
